### ISSUE TITLE
Using GitHub features to manage repository easily

### ISSUE THREAD

**Issue by erdaltsksn** [zalando/go-keyring#50]
Github offers a lot of features via special `.github` folder. Do you have any plan to adapt any of them? For example:

- **Pull Request Template**
- **Issue Templates** (multiple)
- **Workflows** (instead of travis)
- **Dependabot** (_beta_ - Check go.mod file and automatically create a pull request if one of the dependency is outdated.)

All of the above used by my repositories. You can check [https://github.com/erdaltsksn/gh-label/tree/master/.github](https://github.com/erdaltsksn/gh-label/tree/master/.github) to see them.
NOTE: This app `gh-label` uses `go-keyring` so I link it.

If you are willing to adapt, I'm ready to work on it and create a pull request for it.

**Comment by mikkeloscar** [comment]
I think **Pull Request Template** and **Issue Templates** are not needed for this repository as it's limited how many issues we currently get so the structure doesn't need to be enforced at this point IMO.

By **workflows** do you mean **Github Actions** or is it a different thing? I don't mind switching to that over travis just note that we have a little bit of a complex setup in order to test the linux integration so it may be tricky to do in Github actions?

**Dependabot** we're currently trying out for some of our repos. We would like to not enable it here for now as it currently creates more toil than it helps for us.

**Comment by erdaltsksn** [comment]
**GitHub Actions** and **workflows**. They are same. I managed to configure the action.

https://github.com/erdaltsksn/go-keyring/actions/runs/164304657

I think there is a problem with the newer version of Linux.

ref: https://askubuntu.com/questions/1080896/what-replaced-pythons-gnomekeyring-module-in-ubuntu-18-04-bionic

**Comment by mikkeloscar** [comment]
Interesting, at least it would work for another year, and we would have the same issue of 16.04 running EOL on travis at some point (April 2021).

So the **Github Action** change is welcome :)
